# Example of configuration options:
# https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml

# Fix any fixable errors
fix: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

config:
  line-length: false
